### ISSUE TITLE
Zero playouts at trick 10

### ISSUE THREAD

**Issue by ThorvaldAagaard** [Ark223/BGA#1]
I played the default hand and reached this position
![image](https://github.com/Ark223/BGA/assets/10560652/35172efa-b679-49b2-b0ad-8d06cc87f6b1)

Declarer can make the last 3 tricks, but there are no playouts, and thus no stats on the card to play

**Comment by ThorvaldAagaard** [comment]
This will happen if there are no hands, that matching all constraints. I have no good solution other than removing constraints and the evaluate the trick again.

I think what is happening is that MakeMove update details (constraints) but when testing for invalid hands

![image](https://github.com/Ark223/BGA/assets/10560652/37b22043-ff64-4309-a707-963b7a01d319)

The played hands are added before constraints are matched, but I haven't confirmed this,

**Comment by Ark223** [comment]
This issue could be a result of illegal move played by a defender. The game under consideration should proceed according to the real distribution of cards, where user takes responsibility for the overall simulation.
